# ================================================================
# PARETO FRONT PLOT (ENHANCED)
# ================================================================
st.markdown("### 📉 Pareto Front")

# Create figure with improved style
fig, ax = plt.subplots(figsize=(12, 6), dpi=100)
plt.style.use('seaborn-v0_8-darkgrid')

# Plot all solutions with gradient colors
all_solutions = ax.scatter(
    -objectives[:, 0], objectives[:, 1],
    alpha=0.25, s=15, color='#6c757d',
    label='All Solutions',
    rasterized=True
)

# Plot Pareto front with enhanced style
if len(fronts) > 0:
    front0 = fronts[0]
    pareto_api = -objectives[front0, 0]
    pareto_efrf = objectives[front0, 1]
    
    # Sort Pareto points for better line
    sorted_idx = np.argsort(pareto_api)
    pareto_api_sorted = pareto_api[sorted_idx]
    pareto_efrf_sorted = pareto_efrf[sorted_idx]
    
    # Pareto front line with gradient
    ax.plot(
        pareto_api_sorted, pareto_efrf_sorted,
        color='#dc3545', linewidth=2.5, alpha=0.8,
        label='Pareto Front',
        zorder=4
    )
    
    # Pareto points with style
    ax.scatter(
        pareto_api, pareto_efrf,
        color='#dc3545', s=60, edgecolors='white',
        linewidth=0.8, zorder=5, label='Pareto Points'
    )
    
    # Feasible solutions (green stars)
    feasible = constraints[front0]
    feasible_indices = [i for i, f in enumerate(feasible) if f]
    if feasible_indices:
        feasible_api = [pareto_api[i] for i in feasible_indices]
        feasible_efrf = [pareto_efrf[i] for i in feasible_indices]
        ax.scatter(
            feasible_api, feasible_efrf,
            color='#28a745', s=120, marker='*',
            edgecolors='white', linewidth=1.2,
            label=f'Feasible Solutions ({len(feasible_indices)})',
            zorder=6
        )

# Highlight your formulation
if 'api' in locals() and 'efrf' in locals():
    ax.scatter(
        [api], [efrf],
        color='#007bff', s=200, marker='D',
        edgecolors='white', linewidth=2,
        label='Your Formulation',
        zorder=7
    )
    # Add annotation
    ax.annotate(
        f'Your Formulation\n({api:.1f}%, {efrf:.3f})',
        xy=(api, efrf),
        xytext=(api + 1.5, efrf + 0.08),
        fontsize=10,
        fontweight='bold',
        color='#007bff',
        bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='#007bff', alpha=0.7)
    )

# Target point (90.5% API)
target_api = 90.5
# Find EFRF at target from Pareto front
if len(fronts) > 0:
    # Approximate EFRF at target
    target_efrf = np.interp(target_api, pareto_api_sorted, pareto_efrf_sorted)
    ax.scatter(
        [target_api], [target_efrf],
        color='#ffc107', s=250, marker='*',
        edgecolors='#ff6b00', linewidth=2,
        label='⭐ Target: 90.5% API',
        zorder=8
    )
    ax.annotate(
        f'Target: 90.5% API\nEFRF: {target_efrf:.3f}',
        xy=(target_api, target_efrf),
        xytext=(target_api - 3, target_efrf + 0.12),
        fontsize=9,
        fontweight='bold',
        color='#e67e22',
        bbox=dict(boxstyle='round,pad=0.3', facecolor='#fff3cd', edgecolor='#ffc107', alpha=0.8)
    )

# Threshold lines
ax.axhline(y=0.5, color='#e74c3c', linestyle='--', alpha=0.7, linewidth=2, label='EFRF = 0.5 (Limit)')
ax.axhline(y=0.3, color='#f39c12', linestyle=':', alpha=0.5, linewidth=1.5, label='EFRF = 0.3 (Optimal)')

# Fill feasible region
efrf_min = 0
efrf_max = 1.0
ax.fill_between(
    [84, 96], 0.5, 1.0,
    color='#e74c3c', alpha=0.08, label='Infeasible Region'
)
ax.fill_between(
    [84, 96], 0, 0.5,
    color='#28a745', alpha=0.08, label='Feasible Region'
)

# Labels and title
ax.set_xlabel('API Loading (%)', fontsize=13, fontweight='bold', color='#2c3e50')
ax.set_ylabel('EFRF (Capping Risk)', fontsize=13, fontweight='bold', color='#2c3e50')
ax.set_title('NSGA-II Pareto Front — Optimisation Results', fontsize=16, fontweight='bold', color='#2c3e50', pad=15)

# Grid and legend
ax.grid(True, alpha=0.25, linestyle='--')
ax.legend(loc='upper left', fontsize=10, frameon=True, shadow=True, fancybox=True, framealpha=0.9)
ax.set_xlim(84, 96)
ax.set_ylim(0, 1.0)

# Add watermark
ax.text(0.98, 0.02, 'Generated by Hybrid AI Framework', 
        transform=ax.transAxes, fontsize=8, color='gray', alpha=0.4,
        ha='right', va='bottom')

plt.tight_layout()
st.pyplot(fig)
plt.close()

# ================================================================
# SENSITIVITY ANALYSIS PLOT (ENHANCED)
# ================================================================
st.markdown("### 🔍 Sensitivity Analysis")

# Prepare data
base_inputs = [api, mcc, pvpp, mgst, binder, pressure, speed, granule]
_, base_efrf = predict(model, scaler, base_inputs)

features = ['API%', 'MCC%', 'PVPP%', 'Mg-St%', 'Binder%', 'Pressure', 'Speed', 'Granule']
sensitivities = []

for i in range(8):
    test_inputs = base_inputs.copy()
    test_inputs[i] += 0.05 * (base_inputs[i] + 0.1)
    _, efrf_pos = predict(model, scaler, test_inputs)
    
    test_inputs[i] = base_inputs[i] - 0.05 * (base_inputs[i] + 0.1)
    _, efrf_neg = predict(model, scaler, test_inputs)
    
    sensitivities.append(max(abs(efrf_pos - base_efrf), abs(efrf_neg - base_efrf)))

# Sort for tornado plot
sorted_idx = np.argsort(sensitivities)[::-1]
sorted_names = [features[i] for i in sorted_idx]
sorted_values = [sensitivities[i] for i in sorted_idx]

# Create enhanced tornado plot
fig2, ax2 = plt.subplots(figsize=(12, 6), dpi=100)
plt.style.use('seaborn-v0_8-darkgrid')

# Color gradient based on values
max_val = max(sorted_values) if sorted_values else 1
colors = plt.cm.RdYlGn_r(np.array(sorted_values) / (max_val + 0.001))  # Red for high sensitivity, green for low

bars = ax2.barh(sorted_names, sorted_values, color=colors, edgecolor='white', linewidth=0.8)

# Add value labels on bars
for bar, val in zip(bars, sorted_values):
    width = bar.get_width()
    ax2.text(
        width + 0.002, bar.get_y() + bar.get_height()/2,
        f'{val:.4f}',
        va='center', ha='left', fontsize=10, fontweight='bold'
    )

# Add threshold line for average sensitivity
avg_sens = np.mean(sorted_values) if sorted_values else 0
ax2.axvline(x=avg_sens, color='#e74c3c', linestyle='--', alpha=0.7, linewidth=1.5, label=f'Average: {avg_sens:.4f}')

# Labels and title
ax2.set_xlabel('Sensitivity (ΔEFRF)', fontsize=13, fontweight='bold', color='#2c3e50')
ax2.set_ylabel('Parameters', fontsize=13, fontweight='bold', color='#2c3e50')
ax2.set_title('Feature Sensitivity Analysis — Impact on Capping Risk (EFRF)', fontsize=16, fontweight='bold', color='#2c3e50', pad=15)

# Grid and legend
ax2.grid(True, alpha=0.25, linestyle='--', axis='x')
ax2.legend(loc='lower right', fontsize=10, frameon=True, shadow=True)

# Add interpretation note
if sorted_values:
    max_feature = sorted_names[0]
    max_sens = sorted_values[0]
    note = f"💡 Most influential: {max_feature} (ΔEFRF = {max_sens:.4f})"
    ax2.text(0.02, 0.98, note, transform=ax2.transAxes, fontsize=11, 
            fontweight='bold', color='#dc3545',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='white', edgecolor='#dc3545', alpha=0.8),
            va='top')

plt.tight_layout()
st.pyplot(fig2)
plt.close()
